classDiagram
    Modele <|-- Modele_linear_regession
    Modele: -function fonction
    Modele: -float xmin
    Modele: -float xmax
    Modele: -dico popt
    Modele: -dico pcov
    Modele: -dico infos_dic
    Modele: -int nb_pts = 200
    Modele: -int nb_round = 5
    Modele: -str plot_label
    Modele: -bool plot_label_latex
    Modele: -array x
    Modele: -array y
    Modele: -results_format()
    Modele: -update_label()
    Modele: -update_xy()
    Modele: -__init__()
    Modele: -__str__()
    Modele: +get_xmin()
    Modele: +set_xmin()
    Modele: +get_xmax()
    Modele: +set_xmax()
    Modele: +get_nb_pts()
    Modele: +set_nb_pts()
    Modele: +get_nb_round()
    Modele: +set_nb_round()
    Modele: +params()
    Modele: +pcov()
    Modele: +plot()



    class Modele_linear_regession{
        -float chi2, chi2r
        -float ua, ub
        -float level, factor_level
        -float Ua, Ub
        +init()
        +infos()
    }
